# Generated by Django 4.0.4 on 2022-06-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_junkie_app', '0004_remove_movie_favorites_review_user'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='users', to='opinion_junkie_app.movie'),
        ),
    ]
