# Generated by Django 4.0.4 on 2022-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_junkie_app', '0004_remove_movie_favorites_review_user'),
        ('users_app', '0002_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='users', to='opinion_junkie_app.movie'),
        ),
    ]
